# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CaseStudy' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CaseStudy
  pod 'Alamofire', '~> 4.4'
  pod 'ACProgressHUD-Swift', '~> 1.2'
  pod 'SDWebImage', '~>3.8'

  target 'CaseStudyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CaseStudyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
